export const PARAGRAPH = 'PARAGRAPH';
export const MY_IMAGE = 'MY_IMAGE';
export const SHOW_NAV = 'SHOW_NAV';
export const SCROLLED__DOWN = 'SCROLLED__DOWN';
export const SCROLLED__UP = 'SCROLLED__UP';

export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const FETCH_INGREDIENTS_FAILED = 'FETCH_INGREDIENTS_FAILED';
export const PURCHASING = 'PURCHASING';

export const PURCHASE_BURGER_START = 'PURCHASE_BURGER_START';
export const PURCHASE_BURGER_SUCCESS = 'PURCHASE_BURGER_SUCCESS';
export const PURCHASE_BURGER_FAIL = 'PURCHASE_BURGER_FAIL';
export const PURCHASE_INIT = 'PURCHASE_INIT';
export const CANCEL_PURCHASING = 'CANCEL_PURCHASING';

export const FETCH_ORDERS_START = 'FETCH_ORDERS_START';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAIL = 'FETCH_ORDERS_FAIL';

export const IDEAS = 'IDEAS';
export const DELETE = 'DELETE';
export const EDIT = 'EDIT';
export const CATEGORIES = 'CATEGORIES';
export const ADD_CATEGORY = 'ADD_CATEGORY';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';

export const CHANGE_LAYOUT = 'CHANGE_LAYOUT';
export const CHANGE_SPORT = 'CHANGE_SPORT';
export const GET_COUNTRIES = 'GET_COUNTRIES';
export const FETCH_COUNTRIES_FAILED = 'FETCH_COUNTRIES_FAILED';
export const TOGGLE_COUNTRIES = 'TOGGLE_COUNTRIES';
export const GET_LEAGUES = 'GET_LEAGUES';
export const FETCH_LEAGUES_FAILED = 'FETCH_LEAGUES_FAILED';
export const COUNTRY_KEY = 'COUNTRY_KEY';
export const LEAGUE_KEY = 'LEAGUE_KEY';
export const SELECT_CATEGORY = 'SELECT_CATEGORY';
export const GET_FIXTURES = 'GET_FIXTURES';
export const FETCH_FIXTURES_FAILED = 'FETCH_FIXTURES_FAILED';
export const GET_LIVESCORE = 'GET_LIVESCORE';
export const FETCH_LIVESCORE_FAILED = 'FETCH_LIVESCORE_FAILED';
export const GET_ODDS = 'GET_ODDS';
export const REMOVE_LEAGUE_KEY = 'REMOVE_LEAGUE_KEY';
export const MY_LEAGUES = 'MY_LEAGUES';
export const REMOVE_LEAGUE = 'REMOVE_LEAGUE';
export const REMOVE_COUNTRY_KEY = 'REMOVE_COUNTRY_KEY';
export const GET_MATCH_FAILED = 'GET_MATCH_FAILED';
export const MY_MATCH = 'MY_MATCH';
export const REMOVE_MATCH = 'REMOVE_MATCH';

export const LEAGUE_TEAMS = 'LEAGUE_TEAMS';
export const GET_TEAMS_FAILED = 'GET_TEAMS_FAILED';
export const TEAMS_STANDINGS = 'TEAMS_STANDINGS';
export const GET_STANDINGS_FAILED = 'TEAMS_STANDINGS';

